sudo: required
services:
- docker
language: go
go:
- '1.11.4'
go_import_path: kubesphere.io/im
before_script:
- make fmt-check
- make check
- make build
- make compose-up
- sleep 20
script:
- make test
before_deploy:
- make compose-down
deploy:
- provider: script
  script: bash docker_push latest
  on:
    branch: master
    repo: kubesphere/im
- provider: script
  script: bash docker_push $TRAVIS_TAG
  on:
    tags: true
    repo: kubesphere/im
